const sampleAssets = [
  { assetId: 'AST-001', name: 'Web Application Server', type: 'Server', classification: 'Confidential', owner: 'IT Operations', environment: 'Production', department: 'IT', status: 'Active' },
  { assetId: 'AST-002', name: 'Employee Laptops', type: 'Laptop', classification: 'Internal', owner: 'HR Department', environment: 'Production', department: 'HR', status: 'Active' },
  { assetId: 'AST-003', name: 'Core Banking DB', type: 'Database', classification: 'Restricted', owner: 'Database Admin', environment: 'Production', department: 'IT', status: 'Active' },
  { assetId: 'AST-004', name: 'Development API Gateway', type: 'Application', classification: 'Internal', owner: 'Dev Team', environment: 'Development', department: 'Engineering', status: 'Active' },
  { assetId: 'AST-005', name: 'Staging Load Balancer', type: 'Network Device', classification: 'Confidential', owner: 'Network Team', environment: 'Staging', department: 'IT', status: 'Active' },
  { assetId: 'AST-006', name: 'IoT Monitoring Sensors', type: 'IoT Device', classification: 'Internal', owner: 'Facilities', environment: 'Production', department: 'Operations', status: 'Active' },
  { assetId: 'AST-007', name: 'AWS Cloud Infrastructure', type: 'Cloud Service', classification: 'Restricted', owner: 'Cloud Team', environment: 'Production', department: 'IT', status: 'Active' },
  { assetId: 'AST-008', name: 'Mobile Banking App', type: 'Application', classification: 'Restricted', owner: 'Product Team', environment: 'Production', department: 'Product', status: 'Active' },
  { assetId: 'AST-009', name: 'DR Recovery Server', type: 'Server', classification: 'Confidential', owner: 'IT Operations', environment: 'DR', department: 'IT', status: 'Active' },
  { assetId: 'AST-010', name: 'Test Database Cluster', type: 'Database', classification: 'Internal', owner: 'QA Team', environment: 'Testing', department: 'QA', status: 'Active' },
];

const sampleVendors = [
  { vendorId: 'VND-001', name: 'CloudForge Solutions', serviceProvided: 'Cloud Hosting & Infrastructure', locations: ['Mumbai', 'Singapore'], address: { state: 'Maharashtra', country: 'India', pin: '400001' }, taxDetails: { gst: '27AABCU9603R1ZM', pan: 'AABCU9603R' }, criticality: 'C', managedBy: 'IT Department', securityAgreement: true, certifications: ['ISO27001', 'SOC2'], notes: 'Primary cloud infrastructure provider', auditStatus: 'Completed', lastAuditDate: '2025-12-15' },
  { vendorId: 'VND-002', name: 'SecureNet Analytics', serviceProvided: 'SIEM & Security Monitoring', locations: ['Bangalore'], address: { state: 'Karnataka', country: 'India', pin: '560001' }, taxDetails: { gst: '29AADCS1234R1ZP', pan: 'AADCS1234R' }, criticality: 'H', managedBy: 'Security Team', securityAgreement: true, certifications: ['ISO27001'], notes: 'SOC monitoring services', auditStatus: 'In Progress', lastAuditDate: '2025-09-20' },
  { vendorId: 'VND-003', name: 'PayFlow Systems', serviceProvided: 'Payment Gateway', locations: ['Delhi', 'London'], address: { state: 'Delhi', country: 'India', pin: '110001' }, taxDetails: { gst: '07AAECA5678R1ZQ', pan: 'AAECA5678R' }, criticality: 'C', managedBy: 'Finance', securityAgreement: true, certifications: ['PCI-DSS', 'ISO27001'], notes: 'Handles all payment processing', auditStatus: 'Completed', lastAuditDate: '2026-01-10' },
  { vendorId: 'VND-004', name: 'DataPurge Inc', serviceProvided: 'Data Destruction & Disposal', locations: ['Pune'], address: { state: 'Maharashtra', country: 'India', pin: '411001' }, taxDetails: { gst: '27AABCD1234R1ZM', pan: 'AABCD1234R' }, criticality: 'M', managedBy: 'Compliance', securityAgreement: true, certifications: ['ISO22301'], notes: 'Certified data destruction', auditStatus: 'Pending' },
  { vendorId: 'VND-005', name: 'TalentBridge HR', serviceProvided: 'HR & Payroll Software', locations: ['Hyderabad'], address: { state: 'Telangana', country: 'India', pin: '500001' }, taxDetails: { gst: '36AABCH5678R1ZP', pan: 'AABCH5678R' }, criticality: 'L', managedBy: 'HR Department', securityAgreement: false, certifications: [], notes: 'SaaS HR platform', auditStatus: 'Overdue', lastAuditDate: '2024-06-15' },
  { vendorId: 'VND-006', name: 'NetShield Corp', serviceProvided: 'Firewall & DDoS Protection', locations: ['Chennai', 'US'], address: { state: 'Tamil Nadu', country: 'India', pin: '600001' }, taxDetails: { gst: '33AABCN9012R1ZQ', pan: 'AABCN9012R' }, criticality: 'H', managedBy: 'IT Security', securityAgreement: true, certifications: ['ISO27001', 'SOC2'], notes: 'Network perimeter defense', auditStatus: 'Completed', lastAuditDate: '2026-02-01' },
];

const sampleRisks = [
  { riskId: 'RSK-001', title: 'Data Breach via Unpatched Systems', category: 'Cybersecurity', status: 'Open', managementAction: 'Mitigate', likelihood: 4, impact: 5, riskScore: 20, department: 'IT', owner: 'CISO', assignedTo: { name: 'Raj Patel', department: 'IT Security' }, description: 'Unpatched production servers expose critical vulnerabilities', mitigationPlan: 'Implement automated patch management with 72hr SLA', reviewDate: '2026-04-15', rationale: 'Recent CVE disclosures affecting core infrastructure', residualLikelihood: 2, residualImpact: 4, residualScore: 8 },
  { riskId: 'RSK-002', title: 'Third-Party Vendor Data Leakage', category: 'Vendor Risk', status: 'In Progress', managementAction: 'Transfer', likelihood: 3, impact: 5, riskScore: 15, department: 'Procurement', owner: 'CPO', assignedTo: { name: 'Anita Sharma', department: 'Vendor Management' }, description: 'Vendors with access to PII may not maintain adequate security controls', mitigationPlan: 'Enforce contractual security obligations, quarterly vendor audits', reviewDate: '2026-05-01', rationale: 'Two vendors lack ISO27001 certification', residualLikelihood: 2, residualImpact: 3, residualScore: 6 },
  { riskId: 'RSK-003', title: 'Regulatory Non-Compliance (DPDP Act)', category: 'Compliance', status: 'Open', managementAction: 'Mitigate', likelihood: 3, impact: 4, riskScore: 12, department: 'Legal', owner: 'DPO', assignedTo: { name: 'Meera Iyer', department: 'Legal' }, description: 'Failure to meet DPDP Act consent and data processing requirements', mitigationPlan: 'Complete data mapping, implement consent management platform', reviewDate: '2026-04-30', rationale: 'DPDP Act effective 2025; current data processing lacks formal consent management', residualLikelihood: 2, residualImpact: 3, residualScore: 6 },
  { riskId: 'RSK-004', title: 'Business Continuity Failure', category: 'Operational', status: 'In Progress', managementAction: 'Mitigate', likelihood: 2, impact: 5, riskScore: 10, department: 'Operations', owner: 'COO', assignedTo: { name: 'Vikram Singh', department: 'BCP Team' }, description: 'Inadequate DR testing may result in extended downtime', mitigationPlan: 'Quarterly DR drills, update BCP documentation', reviewDate: '2026-06-15', rationale: 'Last DR test revealed 4-hour gap in RTO vs. target', residualLikelihood: 1, residualImpact: 4, residualScore: 4 },
  { riskId: 'RSK-005', title: 'Insider Threat - Privileged Access Abuse', category: 'Cybersecurity', status: 'Open', managementAction: 'Mitigate', likelihood: 3, impact: 4, riskScore: 12, department: 'IT', owner: 'CISO', assignedTo: { name: 'Deepak Kumar', department: 'IAM Team' }, description: 'Privileged users with excessive access may exfiltrate sensitive data', mitigationPlan: 'Implement PAM solution, quarterly access reviews', reviewDate: '2026-04-20', rationale: 'Audit identified 23 users with unnecessary admin privileges', residualLikelihood: 2, residualImpact: 3, residualScore: 6 },
  { riskId: 'RSK-006', title: 'Cloud Misconfiguration', category: 'Cybersecurity', status: 'Open', managementAction: 'Mitigate', likelihood: 4, impact: 4, riskScore: 16, department: 'IT', owner: 'Cloud Lead', assignedTo: { name: 'Priya Nair', department: 'Cloud Ops' }, description: 'Misconfigured S3 buckets and security groups', mitigationPlan: 'Deploy CSPM tool, weekly config scanning', reviewDate: '2026-04-10', rationale: 'Cloud security assessment found 12 critical misconfigs', residualLikelihood: 2, residualImpact: 3, residualScore: 6 },
  { riskId: 'RSK-007', title: 'Phishing Attack Success Rate', category: 'Cybersecurity', status: 'In Progress', managementAction: 'Mitigate', likelihood: 5, impact: 3, riskScore: 15, department: 'HR', owner: 'CISO', assignedTo: { name: 'Suresh Menon', department: 'Security Awareness' }, description: 'Employee susceptibility to phishing remains above threshold', mitigationPlan: 'Monthly phishing simulations, mandatory security training', reviewDate: '2026-05-15', rationale: 'Last simulation showed 18% click rate (target: <5%)', residualLikelihood: 3, residualImpact: 2, residualScore: 6 },
  { riskId: 'RSK-008', title: 'Inadequate Encryption at Rest', category: 'Data Protection', status: 'Open', managementAction: 'Mitigate', likelihood: 2, impact: 5, riskScore: 10, department: 'IT', owner: 'CTO', assignedTo: { name: 'Arun Joshi', department: 'Data Engineering' }, description: 'Legacy databases lack AES-256 encryption', mitigationPlan: 'Encrypt all PII databases, rotate keys quarterly', reviewDate: '2026-06-01', rationale: '3 databases storing PII are unencrypted', residualLikelihood: 1, residualImpact: 3, residualScore: 3 },
  { riskId: 'RSK-009', title: 'Supply Chain Software Risk', category: 'Vendor Risk', status: 'Open', managementAction: 'Avoid', likelihood: 3, impact: 3, riskScore: 9, department: 'Engineering', owner: 'VP Engineering', assignedTo: { name: 'Kavita Reddy', department: 'DevSecOps' }, description: 'Unvetted open-source dependencies may contain vulnerabilities', mitigationPlan: 'Implement SCA scanning in CI/CD pipeline', reviewDate: '2026-05-20', rationale: 'SCA scan identified 47 high-severity vulnerabilities', residualLikelihood: 2, residualImpact: 2, residualScore: 4 },
  { riskId: 'RSK-010', title: 'Physical Security Breach', category: 'Physical', status: 'Closed', managementAction: 'Accept', likelihood: 1, impact: 2, riskScore: 2, department: 'Facilities', owner: 'Facilities Manager', assignedTo: { name: 'Ravi Shankar', department: 'Facilities' }, description: 'Unauthorized physical access to server rooms', mitigationPlan: 'Biometric access controls installed', reviewDate: '2026-07-01', rationale: 'All data centers now have multi-factor physical access controls', residualLikelihood: 1, residualImpact: 1, residualScore: 1 },
];

const sampleKRIs = [
  { kriId: 'KRI-001', name: 'System Uptime', type: 'Lagging', value: 99.7, unit: '%', thresholds: { amber: 99.5, red: 99.0 }, trend: 'Stable', status: 'Safe', linkedRiskId: 'RSK-004' },
  { kriId: 'KRI-002', name: 'Patch Compliance Rate', type: 'Leading', value: 78, unit: '%', thresholds: { amber: 85, red: 70 }, trend: 'Declining', status: 'Warning', linkedRiskId: 'RSK-001' },
  { kriId: 'KRI-003', name: 'Phishing Click Rate', type: 'Lagging', value: 18, unit: '%', thresholds: { amber: 10, red: 20 }, trend: 'Declining', status: 'Warning', linkedRiskId: 'RSK-007' },
  { kriId: 'KRI-004', name: 'Mean Time to Detect (MTTD)', type: 'Lagging', value: 4.2, unit: 'hours', thresholds: { amber: 6, red: 12 }, trend: 'Improving', status: 'Safe', linkedRiskId: 'RSK-001' },
  { kriId: 'KRI-005', name: 'Vendor Compliance Score', type: 'Leading', value: 62, unit: '%', thresholds: { amber: 75, red: 50 }, trend: 'Declining', status: 'Warning', linkedRiskId: 'RSK-002' },
  { kriId: 'KRI-006', name: 'Open Critical Vulnerabilities', type: 'Lagging', value: 14, unit: 'count', thresholds: { amber: 20, red: 30 }, trend: 'Improving', status: 'Safe' },
  { kriId: 'KRI-007', name: 'Data Loss Incidents', type: 'Lagging', value: 0, unit: 'count', thresholds: { amber: 1, red: 3 }, trend: 'Stable', status: 'Safe' },
  { kriId: 'KRI-008', name: 'Access Review Completion', type: 'Leading', value: 45, unit: '%', thresholds: { amber: 80, red: 50 }, trend: 'Declining', status: 'Breached', linkedRiskId: 'RSK-005' },
];

const sampleControls = [
  { controlId: 'CTL-001', name: 'Automated Patch Management', framework: 'ISO 27001', reference: 'A.12.6.1', effectiveness: 'Partially Effective', frequency: 'Weekly', type: 'Preventive', owner: 'IT Operations', status: 'Active', linkedRiskIds: ['RSK-001'], lastAssessment: '2026-02-15' },
  { controlId: 'CTL-002', name: 'Multi-Factor Authentication', framework: 'NIST CSF', reference: 'PR.AC-7', effectiveness: 'Effective', frequency: 'Continuous', type: 'Preventive', owner: 'IAM Team', status: 'Active', linkedRiskIds: ['RSK-005'], lastAssessment: '2026-01-20' },
  { controlId: 'CTL-003', name: 'Vendor Security Assessment', framework: 'ISO 27001', reference: 'A.15.1.1', effectiveness: 'Partially Effective', frequency: 'Quarterly', type: 'Detective', owner: 'Vendor Management', status: 'Active', linkedRiskIds: ['RSK-002'], lastAssessment: '2026-03-01' },
  { controlId: 'CTL-004', name: 'Data Encryption at Rest', framework: 'PCI-DSS', reference: '3.4', effectiveness: 'Ineffective', frequency: 'Continuous', type: 'Preventive', owner: 'Data Engineering', status: 'Under Review', linkedRiskIds: ['RSK-008'], lastAssessment: '2026-02-28' },
  { controlId: 'CTL-005', name: 'Security Awareness Training', framework: 'NIST CSF', reference: 'PR.AT-1', effectiveness: 'Partially Effective', frequency: 'Monthly', type: 'Preventive', owner: 'Security Team', status: 'Active', linkedRiskIds: ['RSK-007'], lastAssessment: '2026-03-10' },
  { controlId: 'CTL-006', name: 'Cloud Security Posture Management', framework: 'CIS Controls', reference: 'CIS.6', effectiveness: 'Effective', frequency: 'Continuous', type: 'Detective', owner: 'Cloud Ops', status: 'Active', linkedRiskIds: ['RSK-006'], lastAssessment: '2026-03-05' },
  { controlId: 'CTL-007', name: 'Business Continuity Testing', framework: 'ISO 22301', reference: '8.5', effectiveness: 'Partially Effective', frequency: 'Quarterly', type: 'Corrective', owner: 'BCP Team', status: 'Active', linkedRiskIds: ['RSK-004'], lastAssessment: '2025-12-20' },
  { controlId: 'CTL-008', name: 'SCA Pipeline Scanning', framework: 'OWASP', reference: 'A06:2021', effectiveness: 'Effective', frequency: 'Continuous', type: 'Detective', owner: 'DevSecOps', status: 'Active', linkedRiskIds: ['RSK-009'], lastAssessment: '2026-03-12' },
];

const sampleTreatments = [
  { treatmentId: 'TRT-001', linkedRiskId: 'RSK-001', linkedRiskTitle: 'Data Breach via Unpatched Systems', type: 'Mitigate', status: 'In Progress', owner: 'Raj Patel', dueDate: '2026-04-15', plan: 'Deploy automated patch management across all production servers with 72-hour SLA for critical patches' },
  { treatmentId: 'TRT-002', linkedRiskId: 'RSK-002', linkedRiskTitle: 'Third-Party Vendor Data Leakage', type: 'Transfer', status: 'Planned', owner: 'Anita Sharma', dueDate: '2026-05-01', plan: 'Negotiate enhanced security clauses in vendor contracts; procure cyber insurance' },
  { treatmentId: 'TRT-003', linkedRiskId: 'RSK-003', linkedRiskTitle: 'Regulatory Non-Compliance (DPDP Act)', type: 'Mitigate', status: 'In Progress', owner: 'Meera Iyer', dueDate: '2026-04-30', plan: 'Complete data mapping exercise and deploy consent management platform' },
  { treatmentId: 'TRT-004', linkedRiskId: 'RSK-005', linkedRiskTitle: 'Insider Threat - Privileged Access Abuse', type: 'Mitigate', status: 'Planned', owner: 'Deepak Kumar', dueDate: '2026-04-20', plan: 'Implement CyberArk PAM solution and enforce quarterly privileged access reviews' },
  { treatmentId: 'TRT-005', linkedRiskId: 'RSK-006', linkedRiskTitle: 'Cloud Misconfiguration', type: 'Mitigate', status: 'Completed', owner: 'Priya Nair', dueDate: '2026-03-15', plan: 'Deployed Wiz CSPM with automated remediation', completionDate: '2026-03-14' },
  { treatmentId: 'TRT-006', linkedRiskId: 'RSK-007', linkedRiskTitle: 'Phishing Attack Success Rate', type: 'Mitigate', status: 'In Progress', owner: 'Suresh Menon', dueDate: '2026-05-15', plan: 'Launch monthly phishing simulations with targeted training' },
  { treatmentId: 'TRT-007', linkedRiskId: 'RSK-004', linkedRiskTitle: 'Business Continuity Failure', type: 'Mitigate', status: 'In Progress', owner: 'Vikram Singh', dueDate: '2026-06-15', plan: 'Conduct quarterly DR drills and update recovery runbooks' },
  { treatmentId: 'TRT-008', linkedRiskId: 'RSK-009', linkedRiskTitle: 'Supply Chain Software Risk', type: 'Avoid', status: 'Completed', owner: 'Kavita Reddy', dueDate: '2026-03-20', plan: 'Integrated Snyk SCA into CI/CD pipeline', completionDate: '2026-03-18' },
];

const sampleRiskAppetite = [
  { category: 'Cybersecurity', maxScore: 12, action: 'Immediate escalation to CISO; mandatory mitigation within 30 days', linkedKRIs: ['KRI-001', 'KRI-002', 'KRI-004'] },
  { category: 'Compliance', maxScore: 9, action: 'DPO review required; remediation plan within 15 days', linkedKRIs: ['KRI-005'] },
  { category: 'Operational', maxScore: 15, action: 'COO review; BCP update required', linkedKRIs: ['KRI-001'] },
  { category: 'Vendor Risk', maxScore: 10, action: 'Vendor audit trigger; contract review', linkedKRIs: ['KRI-005'] },
  { category: 'Data Protection', maxScore: 8, action: 'Encryption mandate; data classification review', linkedKRIs: ['KRI-007'] },
  { category: 'Physical', maxScore: 6, action: 'Facilities review; access control upgrade', linkedKRIs: [] },
];

module.exports = { sampleAssets, sampleVendors, sampleRisks, sampleKRIs, sampleControls, sampleTreatments, sampleRiskAppetite };
